[project]
name = "multiagent-st"
version = "0.1.0"
description = "Multi-agent streamlit app"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "python-dotenv>=0.9.0",
    "streamlit>=1.32.0",
    "openai>=1.3.7",
]
